### Users
### User Create
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###Sessions
### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}