### Users
### User Create
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###Sessions
### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###Entries
### Entries Index
GET http://localhost:3000/entries.json 

### Entries Show
GET http://localhost:3000/entries/1.json

### Entries Post
POST http://localhost:3000/entries.json 
Content-Type: application/json

{
  "user_id": 1,
  "lure_id": 1,
  "location": "lake",
  "weather": "sunny",
  "notes": "nothing to note",
  "date": 20210101
}

### Entries Update
PATCH http://localhost:3000/entries/8.json 
Content-Type: application/json

{
  "user_id": 2,
  "lure_id": 2,
  "location": "river",
  "weather": "rainy",
  "notes": "shit day",
  "date": 20210102
}

### Entries Destroy
DELETE http://localhost:3000/entries/8.json