@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTcwMDB9.PgO5n6osqfzFGP1mcHKsgA78B5yEfZ1-xId2YM4_G58
@jwt2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjgwMTY2Mzh9.FKJ8YjQFPWvecj1ucqrbm2LCIzrrcHDg6jqt5EZQXlA

### Users
### User Create
POST http://localhost:3000/users.json 
Content-Type: application/json 

{
  "name": "test2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###Sessions
### Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password"
}

###Entries
### Entries Index
GET http://localhost:3000/entries.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTcwMDB9.PgO5n6osqfzFGP1mcHKsgA78B5yEfZ1-xId2YM4_G58

### Entries Show
GET http://localhost:3000/entries/1.json

### Entries Post
POST http://localhost:3000/entries.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTcwMDB9.PgO5n6osqfzFGP1mcHKsgA78B5yEfZ1-xId2YM4_G58
Content-Type: application/json

{
  "user_id": 1,
  "location": "lake",
  "weather": "sunny",
  "notes": "nothing to note",
  "date": 20210101
}

### Entries Update
PATCH http://localhost:3000/entries/9.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjgwMTY2Mzh9.FKJ8YjQFPWvecj1ucqrbm2LCIzrrcHDg6jqt5EZQXlA
Content-Type: application/json

{
  "user_id": 1,
  "lure_ids": 2,
  "location": "river",
  "weather": "hot",
  "notes": "shit day",
  "date": 20210102
}

### Entries Destroy
DELETE http://localhost:3000/entries/9.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTcwMDB9.PgO5n6osqfzFGP1mcHKsgA78B5yEfZ1-xId2YM4_G58

### FISH
### Fish Index
GET http://localhost:3000/fishes.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjgwMTY2Mzh9.FKJ8YjQFPWvecj1ucqrbm2LCIzrrcHDg6jqt5EZQXlA

### Fish Show
GET http://localhost:3000/fishes/3.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgwMTcwMDB9.PgO5n6osqfzFGP1mcHKsgA78B5yEfZ1-xId2YM4_G58

### Fish Create
POST http://localhost:3000/fishes.json 
Content-Type: application/json

{
  "entry_id": 9,
  "user_id": 1,
  "lure_id": 1,
  "species": "bluefin",
  "length": 57,
  "weight": 220
}

### Fish Update
PATCH http://localhost:3000/fishes/3.json 
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "species": "smallmouth",
  "entry_id": 10
}

### Fish Destroy
DELETE http://localhost:3000/fishes/3.json 
Authorization: Bearer {{jwt}}

### LURES

### Lure Index
GET http://localhost:3000/lures.json 

### Lure Show
GET http://localhost:3000/lures/1.json 

### Lure Create
POST http://localhost:3000/lures.json 
Content-Type: application/json

{
  "entry_id": 9,
  "user_id": 1,
  "name": "beetlespin",
  "color": "black"
}